### ISSUE TITLE
Feature Request for adding Gherkin Support

### ISSUE THREAD

**Issue by lindt** [rtfd/readthedocs.org#2096]
## Details

I normally do not write documentation in rst or md files, because I fear it outdates too fast. All my documentation is within some gherkin/feature files.
I would now love to generate the readthedocs documentation based on the feature files.
Gherkin->MD converter is no problem.
How could I achieve this?
Is this way appreciated or is readthedocs not supposed to be used that way?

Sorry for such a basic question. Couldn't find anything related to that topic online. Hope to find an easy solution. Currently think sphinx is too heavy for that.

Project on ReadTheDocs: https://readthedocs.org/projects/compose-plantuml/  (Empty)
Project on GitHub: https://github.com/funkwerk/compose_plantuml
Gherkin-Files:
- https://github.com/funkwerk/compose_plantuml/blob/master/features/boundaries.feature
- https://github.com/funkwerk/compose_plantuml/blob/master/features/link_graph.feature

**Comment by agjohnson** [comment]
This currently isn't supported, we don't have a pattern that would fit this very well. You could always handle generation to MD manually, but this adds barriers to the authoring process. I'd suggest you look into writing a Sphinx extension for this. You'd have to handle docutil node generation on your own, as well as parsing of the feature files.

Someone might have some more to add here, I'll leave this open as a community feature. It shouldn't require RTD at however.

**Comment by lindt** [comment]
sphinx is IMHO for documentation of source code; the internal api of a project.
I aim more for the external api and consider the source as a black box and subject of change anyway.

have seen, that there are already some docker custom builder hooks.
[readthedocs.doc_builder.environments.DockerEnvironment](https://read-the-docs.readthedocs.org/en/latest/api/doc_builder.html)
Are there some examples of how to use it? It reads as it would be sufficient. I could implement the feature->md/html converter within a docker container and then all projects with feature files could be served by readthedocs.

Could I do this just by using _readthedocs.yml_? Haven't found anything. Sorry for such basic questions.

Would love to have a .yml like this.
```yml
formats:
 - pdf
 - html
chapters:
  features:
    - name: Features
    - docker_image: some_docker/image:v42
    - docker_command: --html features/*.feature
  plantuml:
    - name: Model
    - docker_image: another_docker/image:v23
    - docker_command: --html model/*.uml
  api:
    - name: Api
    - docker_image: swagger_docker/image:v1
    - docker_command: --html **/*.swagger_ui_json
  sphinx:
    - name: Source
    - sphinx: src/**/*.{py,c}
```
