### ISSUE TITLE
don't add badge_only.css or allow disabling

### ISSUE THREAD

**Issue by jab** [rtfd/readthedocs.org#2348]
It looks like readthedocs is adding
```html
<link rel="stylesheet" href="https://media.readthedocs.org/css/badge_only.css" type="text/css" />
```
to my generated docs without my opting into this or giving me a way to opt out, causing images I'm including to look bad on mobile.

I worked around it by adding
```css
@media screen and (max-width: 768px) {
  img {
    width: auto;
  }
}
```
to my custom.css, but it'd be great if users didn't have to do this.
