### ISSUE TITLE
Upgrade Sphinx version on Conda

### ISSUE THREAD

**Issue by ericholscher** [rtfd/readthedocs.org#2714]
Blocked on #2713 -- we should upgrade our conda version of `sphinx_rtd_theme` and `sphinx` to match our virtualenv versions.

**Comment by humitos** [comment]
`sphinx_rtd_theme` was already updated in conda forge at https://github.com/conda-forge/sphinx_rtd_theme-feedstock/pull/6

`sphinx` is still blocked because of windows version at https://github.com/conda-forge/sphinx-feedstock/pull/10

**Comment by humitos** [comment]
Finally, the issue with sphinx in conda-forge was fixed https://github.com/conda/conda-build/issues/1845, although the Windows version is still with an issue, https://github.com/conda-forge/sphinx-feedstock/issues/16 but I think it doesn't affect us.

A simple `environment.yml` example working:

```yml
name: sphinx-test

channels:
  - conda-forge
  - default

dependencies:
  - python=3.6
  - sphinx=1.5.3
  - sphinx_rtd_theme=0.2.4
```
