### ISSUE TITLE
Builds ignore yaml config settings

### ISSUE THREAD

**Issue by cas--** [rtfd/readthedocs.org#4100]
## Details

* Read the Docs project URL: https://readthedocs.com/projects/niteo-minisites
* Build URL (if applicable): https://readthedocs.com/projects/niteo-minisites/builds/109251/
* Read the Docs username (if applicable): cas--

## Expected Result

Add a `.readthedocs.yaml` config file and use the settings for the build

```yaml
formats:
    - pdf

python:
    version: 3
    setup_py_install: true
    pip_install: true
    extra_requirements:
        - docs

requirements_file: .readthedocs.requirements.txt
```
and `.readthedocs.requirements.txt` contains:

`sphinxcontrib.spelling`

## Actual Result

The build fails due to missing `sphinxcontrib.spelling`. It seems to only honor settings from project `Advanced Settings` page.

If I set the requirements file in the web interface it works
