### ISSUE TITLE
Intermittent failures for time or memory usage

### ISSUE THREAD

**Issue by arthall** [rtfd/readthedocs.org#4251]
## Details

* Read the Docs project URL: https://oracle-cloud-infrastructure-python-sdk.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/
* Read the Docs username (if applicable): arthall

## Expected Result

Project would build without issues, or all builds would fail for the same reason.

## Actual Result

The build intermittently fails.  Sometimes it times out and other times it runs out of memory.

This build failed due to a time out: https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/7276429/

But the next build of the docs succeed in only 580 seconds: https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/7276494/

This one failed due to memory consumption: https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/7208386/

The next one passed: https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/7208465/

**Comment by stsewd** [comment]
Please see https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html

**Comment by arthall** [comment]
I have added a .readthedocs.yml file which turns off the downloadable docs and points to a simplified docs requirements file.  Seem to address the resource issue.  I'm still not sure why some builds didn't seem to be hitting the resource limits while other were, but the docs are building again.

If I see failures again in the future, I'll reopen this issue.

**Comment by arthall** [comment]
Our last builds for the docs failed 3 times, one for latest and twice for stable, before they passed.

https://readthedocs.org/projects/oracle-cloud-infrastructure-python-sdk/builds/

I've implemented the suggestions here: https://docs.readthedocs.io/en/latest/guides/build-using-too-many-resources.html.  The successful builds are much quicker than they used to be, but they still sometimes fail due to constraints.  Are there any other things we can do to get the builds to succeed regularly?  The concern is that we will add a new service to the docs and that will cause the builds to always fail.

Here is my .readthedocs.yml
```
# Read The Docs config
# - http://docs.readthedocs.io/en/latest/yaml-config.html

# python version
python:
    version: 3.5
    setup_py_install: true
   
# Just the HTML and indexing
formats:
    - none

# Limit the requirements to building the docs
requirements_file: docs/requirements.txt
```
https://github.com/oracle/oci-python-sdk/blob/v1.4.4/.readthedocs.yml

and the contents of docs/requirements.txt
```
sphinx-rtd-theme==0.2.5b2
sphinx==1.6.4
```
https://github.com/oracle/oci-python-sdk/blob/v1.4.4/docs/requirements.txt
