### ISSUE TITLE
Integrate Transifex with Travis

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4463]
We do a bad job of keeping translation files up to date. Let's automate it!

Docs here:
https://docs.transifex.com/integrations/github/

The problem is that these docs are bad. This would result in every PR pushing up translations. This is bad, we probably only want this on pushes to `master`. That's cool, lets just make a contrib script or something that emulates the steps in the Travis config in the example above and just check for `master` branch before pushing.

**Comment by sriks123** [comment]
Hello @agjohnson can I work on this issue ?

**Comment by chenrui333** [comment]
I wonder if I can help with this, currently I am thinking of adopting the similar workflow in my company as well.

**Comment by stsewd** [comment]
> The problem is that these docs are bad. This would result in every PR pushing up translations.

Actually you can do that in travis https://docs.travis-ci.com/user/conditional-builds-stages-jobs/

Also, I just saw this https://docs.travis-ci.com/user/deployment/transifex/ (not sure if it's updated)

**Comment by chenrui333** [comment]
good to know that they have deployment script.

**Comment by chenrui333** [comment]
but we also need to pull the docs as well.

**Comment by rffontenelle** [comment]
I provided a travis-ci YAML file in the above PR, but i was told RTD is now using circle-ci. Having that said, ~I suggest renaming this issue Travis -> CircleCI~ (ok, renamed by stsewd).

Also, here is an untested job description to be used in [.circleci/config.yml](https://github.com/readthedocs/readthedocs.org/blob/master/.circleci/config.yml):

```
  update-translations:
    docker:
      - image: 'cimg/python:3.6'
    steps:
      - pip3 install -r requirements/docs.txt -r requirements/pip.txt transifex-client
      - cd docs
      - sphinx-build -b gettext . _build/locale
      - echo $'[https://www.transifex.com]\napi_hostname = https://api.transifex.com\nhostname = https://www.transifex.com\npassword = '"$TRANSIFEX_API_TOKEN"$'\nusername = api\n' > ~/.transifexrc
      - rm .tx/config
      - sphinx-intl create-txconfig
      - sphinx-intl update-txconfig-resources --transifex-project-name=readthedocs-docs --locale-dir locale --pot-dir _build/locale
      - tx push -s
```

TRANSIFEX_API_TOKEN is the variable containing the API token to be used by `transifex-client`. A maintainer of readthedocs-docs organization in Transifex needs to [generate a API token](https://www.transifex.com/user/settings/api/) and set it in repository settings in CircleCI.

If a test returns the error saying that only (Transifex) project maintainer can push source strings, it is a great progress!

While a similar set of statements works on TravisCI (see PR!), I wasn't able to test it on CircleCI (a similar  because of some obstacles in CircleCI (I mentioned in there).

Anyone willing to test it?
