### ISSUE TITLE
Add submodule configuration

### ISSUE THREAD

**Issue by agjohnson** [rtfd/readthedocs.org#4464]
Migrated from https://github.com/rtfd/readthedocs-build/issues/30

Seems a number of projects are hitting issues with submodule clone steps, and this should be configurable in our config. Because git doesn't provide the mechanism for optional submodules, we can do something like:

```yaml
submodules:
  include: []
  recursive: false
```

as implicit default. And:

```yaml
submodules:
  include:
    - foo/
    - bar/
```

As include example.

```yaml
submodules:
  exclude:
    - foo/
```

^ is the exclude example.

Legacy projects implemented before this change would have an implicit configuration of:

```yaml
submodules:
  include: all
  recursive: true
```

It's not possible to include and exclude submodules, this is a validation error.

This would eventually alter the code that rtfd/readthedocs.org uses for submodule cloning, and would only selectively clone things? The changes there are likely moving to specific submodule clone commands.

- [ ] Currently submodule cloning takes place in the git checkout step. This will need to be moved to a new step after we parse the configuration
- [ ] New behavior will be to not clone submodules automatically
- [ ] If possible, we won't recursively clone as well. Maybe this is another option on the spec?
- [ ] We'll add a new `project.Feature`, plus migration, to lock old users into the old behavior (all submodules are cloned)
- [ ] We can perhaps also detect that a project has submodules that won't be cloned and raise a warning. This warning shouldn't be a build failure, but a notification on-site/through email?
