### ISSUE TITLE
Navbar display different when hosted on readthedocs.org

### ISSUE THREAD

**Issue by thomthom** [rtfd/readthedocs.org#5090]
## Details

* Read the Docs project URL: https://rubocop-sketchup.readthedocs.io/en/latest/
* Build URL (if applicable):
* Read the Docs username (if applicable):

## Expected Result

My `mkdocs.yml`:

```yml
site_name: "RuboCop SketchUp: SketchUp Extension Best Practices"
repo_url: https://github.com/sketchup/rubocop-sketchup
edit_uri: edit/master/manual/
copyright: "Copyright &copy; 2017-2018 Trimble Inc. SketchUp and contributors"
docs_dir: manual
nav:
- Home: index.md
- Installation: installation.md
- Basic Usage: basic_usage.md
- Cops: cops.md
- Formatters: formatters.md
- Configuration: configuration.md
- Integration with other tools: integration_with_other_tools.md
- Contributing: contributing.md
- Development: development.md
- Cops Documentation:
    - Requirements Cops: cops_requirements.md
    - Deprecations Cops: cops_deprecations.md
    - Performance Cops: cops_performance.md
    - Suggestions Cops: cops_suggestions.md
extra_css:
  - css/extra.css
markdown_extensions:
  - admonition
theme: readthedocs
```

Here's what I see when I build manually:

![2019-01-10_14h50_25](https://user-images.githubusercontent.com/192418/50972751-afbe5c80-14e7-11e9-9f65-e1176ca500f4.png)

The navbar layout matches my config file.

## Actual Result

However, when I view the docs on readthedocs.ord the navbar is flattened and appear out of order:

![2019-01-10_14h50_34](https://user-images.githubusercontent.com/192418/50972766-b6e56a80-14e7-11e9-93f5-f8e7d0cd2874.png)

Is this a config issue? Or version mismatch?

```
PS C:\Users\Thomas\SourceTree\rubocop-sketchup> mkdocs -V
mkdocs, version 1.0.4 from c:\users\thomas\appdata\local\programs\python\python36-32\lib\site-packages\mkdocs (Python 3.6)
```
