### ISSUE TITLE
New builds crashing at conda environment.yml install phase

### ISSUE THREAD

**Issue by chrisjsewell** [rtfd/readthedocs.org#5387]
## Details

* Read the Docs project URL: https://ipypublish.readthedocs.io
* Build URL (if applicable): https://readthedocs.org/projects/ipypublish/builds/?page=1
* Read the Docs username (if applicable): cjsewell

## Expected Result

Successful install of Conda dependencies from environment.yaml

## Actual Result

All builds from the last few days fail with:

```
[rtd-command-info] start-time: 2019-02-28T02:27:14.102739Z, end-time: 2019-02-28T02:29:38.601383Z, duration: 144, exit-code: 247
conda env create --quiet --name latest --file /home/docs/checkouts/readthedocs.org/user_builds/ipypublish/checkouts/latest/docs/environment.yaml
Solving environment: ...working...
```

There has been on change in the conda dependencies from the last successful build,
so I assume something has changed on the conda/rtd end?

From this related issues #5098, it looks like I may need to ask you to increase the memory limit?

**Comment by stsewd** [comment]
Looks like a missing dependency

> ModuleNotFoundError: No module named 'matplotlib'

**Comment by chrisjsewell** [comment]
@stsewd thanks for the quick reply.

That is only in the most recent [Build #8690163](https://readthedocs.org/projects/ipypublish/builds/8690163/) (just created),
where I try using `system_packages: true` for the `matplotlib`  and `pandas` dependencies.
Am I writing the configuration file wrong?

```yaml
version: 2

conda:
  environment: docs/environment.yaml

python:
  version: 3.6
  install:
    - method: pip
      path: .
  system_packages: true
```

**Comment by stsewd** [comment]
Maybe they are interfering from the packages in the docker image, can you remove the `system_packages` option (default is false and looks like you don't need that option)?

**Comment by chrisjsewell** [comment]
ok fixed by moving all but the non-python (pandoc) dependency to an extras_requirement:

.readthedocs.yml:

```yaml
version: 2

conda:
  environment: docs/environment.yaml

python:
  version: 3.6
  install:
    - method: pip
      path: .
      extra_requirements:
          - rtd
```

docs/environment.yaml:

```yaml
channels:
  - conda-forge
dependencies:
  - python =3.6
  - pandoc
```

Two things I noted are:

1. Despite setting the python version in the .readthedocs.yml,
    it still builds a python 3.7 environment, unless I set python in the environment.yaml
2. In [Build #8690254](https://readthedocs.org/projects/ipypublish/builds/8690254/),
    I again tried to use `system_packages: true` (instead of pip installing matplotlib),
    but again, it did not find it. Perhaps that mechanism is broken?
