### ISSUE TITLE
Point users to use a configuration file from the import menu

### ISSUE THREAD

**Issue by stsewd** [rtfd/readthedocs.org#5414]
I was thinking we can put a link just next to the `Edit advanced options` or as a help text.

![screenshot_2019-03-06 add a project read the docs 1](https://user-images.githubusercontent.com/4975310/53922895-31dc8480-4044-11e9-9f29-7695020165c2.png)

**Comment by dhruvkb** [comment]
From a design point of view, I'd suggest a help text would be more efficient because a link to the advanced settings page would not exist before the project is added and clicking 'Next' to add the project would redirect the user to a different page anyway.

I'm new here and not very certain of the design aspect, but this seems like a good **first issue**. Can I work on this after we reach a design consensus?

**Comment by dojutsu-user** [comment]
Hi @dhruvkb 
@stsewd had already assigned this issue to himself and @davidfischer.
I would suggest you to please look into another issues.
Thanks

**Comment by stsewd** [comment]
@dhruvkb thanks for the interest, but as mentioned, this work is already assigned. And for clarification, we are talking about this configuration file https://docs.readthedocs.io/en/stable/config-file/index.html

**Comment by davidfischer** [comment]
Of the configurable options on the import screen's "advanced options", the only one that can be configured in the YAML file is the documentation type (sphinx, mkdocs, etc). That's also the only one that really **must** be configured before a project can be built. All the others are just metadata about the project.

![Screen Shot 2019-03-12 at 4 40 41 PM](https://user-images.githubusercontent.com/185043/54243451-b9634100-44e5-11e9-9f88-43bede3b70b8.png)

## Proposal

- I think we should completely remove the the "advanced project options" checkbox and form. This is totally unnecessary as all those things other than the documentation type can be tuned after the project is imported and built.
- Instead, we should point people to the YAML config file documentation on the manual import page and we should even provide a sample config file with the most common options. Something like this:
```yaml
version: 2
formats: all

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

python:
  version: 3.7
  
  # Python requirements required to build your docs
  install:
    - requirements: docs/requirements.txt
```
