### ISSUE TITLE
Building issue: Asked to contact the support

### ISSUE THREAD

**Issue by Ahleroy** [rtfd/readthedocs.org#5532]
## Details

* Read the Docs project URL: https://deeplodocus.readthedocs.io/en/master/
* Build URL (if applicable): 
* Read the Docs username (if applicable): AhLeroy
* Build it : 8803998

## Expected Result

I was expecting my build to succeed.

Here is my readthedocs.yml : 
```
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml


# Optionally set the version of Python and requirements required to build your docs
#python:
#   version: 3.7
#   install:
#      - requirements: docs/requirements.txt
#      - method: setuptools
#        path: package
#   system_packages: true

mkdocs:
  configuration: docs/mkdocs.yml

# Build ePub (pdf is currently failing)
formats:
  - epub

build:
  image: latest

## pip requirements file for building sphinx docs (e.g. nbsphinx)
#requirements_file: docs/requirements.txt

# can also specify a conda env file if pip isn't enough, for example:
# conda:
#   file: environment.yml

# Use python 3 for building
python:
  version: 3.7
  install:
    - requirements: docs/requirements.txt
```

and my requirements.txt : 
```
mkdocs>=1.0.4
```
My mkdocs.yml:
```
site_name: Deeplodocus Documentation
site_description: 'Documentation of Deeplodocus, Flexible and Modular Deep Learning Framework.'
site_url: http://deeplodocus.org
# google_analytics: ['UA-36723568-3', 'mkdocs.org']

repo_url: http://github.com/Deeplodocus/deeplodocus
edit_uri: http://github.com/Deeplodocus/deeplodocus

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python

# theme: readthedocs
docs_dir: 'docs/templates'

nav:
    - Home: index.md
    - Data: data.md
    - About: about.md
```

## Actual Result
```
Read the Docs build information
Build id: 8803998
Project: deeplodocus
Version: master
Commit: 6d41a7860eb80a39b29a8b29adbb211b73a6d4c4
Date: 2019-03-24T00:16:38.260801Z
State: finished
Success: False


[rtd-command-info] start-time: 2019-03-24T00:16:38.692282Z, end-time: 2019-03-24T00:16:38.705393Z, duration: 0, exit-code: 0
git remote set-url origin https://github.com/Deeplodocus/deeplodocus.git


[rtd-command-info] start-time: 2019-03-24T00:16:38.839861Z, end-time: 2019-03-24T00:16:39.297620Z, duration: 0, exit-code: 0
git fetch --tags --prune --prune-tags --depth 50
From https://github.com/Deeplodocus/deeplodocus
   6019a11..6d41a78  master     -> origin/master

[rtd-command-info] start-time: 2019-03-24T00:16:39.525247Z, end-time: 2019-03-24T00:16:39.541599Z, duration: 0, exit-code: 0
git checkout --force origin/master
Previous HEAD position was 6019a11 Merge pull request #197 from Ahleroy/master
HEAD is now at 6d41a78 Merge pull request #200 from Ahleroy/master

[rtd-command-info] start-time: 2019-03-24T00:16:39.608968Z, end-time: 2019-03-24T00:16:39.624978Z, duration: 0, exit-code: 0
git clean -d -f -f


[rtd-command-info] start-time: 2019-03-24T00:16:44.194823Z, end-time: 2019-03-24T00:16:48.637871Z, duration: 4, exit-code: 0
python3.7 -mvirtualenv --system-site-packages --no-download /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master
Using base prefix '/home/docs/.pyenv/versions/3.7.1'
New python executable in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/bin/python3.7
Not overwriting existing python script /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/bin/python (you must use /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/bin/python3.7)
Installing setuptools, pip, wheel...
done.

[rtd-command-info] start-time: 2019-03-24T00:16:48.713008Z, end-time: 2019-03-24T00:16:49.606225Z, duration: 0, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/.cache/pip pip
Requirement already up-to-date: pip in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (19.0.3)

[rtd-command-info] start-time: 2019-03-24T00:16:49.664626Z, end-time: 2019-03-24T00:17:00.586828Z, duration: 10, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/bin/python -m pip install --upgrade --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/.cache/pip -I Pygments==2.3.1 setuptools<41 docutils==0.14 mock==1.0.1 pillow==5.4.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.8.1 recommonmark==0.5.0 mkdocs==0.17.3
Collecting Pygments==2.3.1
  Using cached https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl
Collecting setuptools<41
  Using cached https://files.pythonhosted.org/packages/d1/6a/4b2fcefd2ea0868810e92d519dacac1ddc64a2e53ba9e3422c3b62b378a6/setuptools-40.8.0-py2.py3-none-any.whl
Collecting docutils==0.14
  Using cached https://files.pythonhosted.org/packages/36/fa/08e9e6e0e3cbd1d362c3bbee8d01d0aedb2155c4ac112b19ef3cae8eed8d/docutils-0.14-py3-none-any.whl
Collecting mock==1.0.1
Collecting pillow==5.4.1
  Using cached https://files.pythonhosted.org/packages/ae/2a/0a0ab2833e5270664fb5fae590717f867ac6319b124160c09f1d3291de28/Pillow-5.4.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting alabaster!=0.7.5,<0.8,>=0.7
  Using cached https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
Collecting commonmark==0.8.1
  Using cached https://files.pythonhosted.org/packages/ab/ca/439c88039583a29564a0043186875258e9a4f041fb5c422cd387b8e10175/commonmark-0.8.1-py2.py3-none-any.whl
Collecting recommonmark==0.5.0
  Using cached https://files.pythonhosted.org/packages/9b/3d/92ea48401622510e57b4bdaa74dc9db2fb9e9e892324b48f9c02d716a93a/recommonmark-0.5.0-py2.py3-none-any.whl
Collecting mkdocs==0.17.3
  Using cached https://files.pythonhosted.org/packages/79/52/f395c87a3ec799586a8cdf8f360a96ccbbf7f119200204d17166cc4fb097/mkdocs-0.17.3-py2.py3-none-any.whl
Collecting future (from commonmark==0.8.1)
Collecting sphinx>=1.3.1 (from recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/7d/66/a4af242b4348b729b9d46ce5db23943ce9bca7da9bbe2ece60dc27f26420/Sphinx-1.8.5-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from mkdocs==0.17.3)
Collecting livereload>=2.5.1 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/ae/dd/f518bb99d84a3d26f45c281030b4d74b8cbe23bf8ad311b42e413aa33e51/livereload-2.6.0-py2.py3-none-any.whl
Collecting tornado<5.0,>=4.1 (from mkdocs==0.17.3)
Collecting Markdown>=2.3.1 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/7a/6b/5600647404ba15545ec37d2f7f58844d690baf2f81f3a60b862e48f29287/Markdown-3.0.1-py2.py3-none-any.whl
Collecting click>=3.3 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting Jinja2>=2.7.1 (from mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting six>=1.5 (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Collecting requests>=2.0.0 (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting packaging (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/91/32/58bc30e646e55eab8b21abf89e353f59c0cc02c417e42929f4a9546e1b1d/packaging-19.0-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/d4/6c/8a935e2c7b54a37714656d753e4187ee0631988184ed50c0cf6476858566/snowballstemmer-1.2.1-py2.py3-none-any.whl
Collecting babel!=2.0,>=1.3 (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/b8/ad/c6f60602d3ee3d92fbed87675b6fb6a6f9a38c223343ababdb44ba201f10/Babel-2.6.0-py2.py3-none-any.whl
Collecting sphinxcontrib-websupport (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/52/69/3c2fbdc3702358c5b34ee25e387b24838597ef099761fc9a42c166796e8f/sphinxcontrib_websupport-1.1.0-py2.py3-none-any.whl
Collecting imagesize (from sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/fc/b6/aef66b4c52a6ad6ac18cf6ebc5731ed06d8c9ae4d3b2d9951f261150be67/imagesize-1.1.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.7.1->mkdocs==0.17.3)
  Using cached https://files.pythonhosted.org/packages/98/7b/ff284bd8c80654e471b769062a9b43cc5d03e7a615048d96f4619df8d420/MarkupSafe-1.1.1-cp37-cp37m-manylinux1_x86_64.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.0.0->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting urllib3<1.25,>=1.21.1 (from requests>=2.0.0->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting certifi>=2017.4.17 (from requests>=2.0.0->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting pyparsing>=2.0.2 (from packaging->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/de/0a/001be530836743d8be6c2d85069f46fecf84ac6c18c7f5fb8125ee11d854/pyparsing-2.3.1-py2.py3-none-any.whl
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx>=1.3.1->recommonmark==0.5.0)
  Using cached https://files.pythonhosted.org/packages/61/28/1d3920e4d1d50b19bc5d24398a7cd85cc7b9a75a490570d5a30c57622d34/pytz-2018.9-py2.py3-none-any.whl
Installing collected packages: Pygments, setuptools, docutils, mock, pillow, alabaster, future, commonmark, six, chardet, idna, urllib3, certifi, requests, pyparsing, packaging, snowballstemmer, pytz, babel, MarkupSafe, Jinja2, sphinxcontrib-websupport, imagesize, sphinx, recommonmark, PyYAML, tornado, livereload, Markdown, click, mkdocs
Successfully installed Jinja2-2.10 Markdown-3.0.1 MarkupSafe-1.1.1 PyYAML-5.1 Pygments-2.3.1 alabaster-0.7.12 babel-2.6.0 certifi-2019.3.9 chardet-3.0.4 click-7.0 commonmark-0.8.1 docutils-0.14 future-0.17.1 idna-2.8 imagesize-1.1.0 livereload-2.6.0 mkdocs-1.0.4 mock-1.0.1 packaging-19.0 pillow-5.4.1 pyparsing-2.3.1 pytz-2018.9 recommonmark-0.5.0 requests-2.21.0 setuptools-40.8.0 six-1.12.0 snowballstemmer-1.2.1 sphinx-1.8.5 sphinxcontrib-websupport-1.1.0 tornado-6.0.2 urllib3-1.24.1

[rtd-command-info] start-time: 2019-03-24T00:17:00.644726Z, end-time: 2019-03-24T00:17:01.422140Z, duration: 0, exit-code: 0
/home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/bin/python -m pip install --exists-action=w --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/.cache/pip -r docs/requirements.txt
Requirement already satisfied: mkdocs>=1.0.4 in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from -r docs/requirements.txt (line 1)) (1.0.4)
Requirement already satisfied: Jinja2>=2.7.1 in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from mkdocs>=1.0.4->-r docs/requirements.txt (line 1)) (2.10)
Requirement already satisfied: livereload>=2.5.1 in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from mkdocs>=1.0.4->-r docs/requirements.txt (line 1)) (2.6.0)
Requirement already satisfied: click>=3.3 in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from mkdocs>=1.0.4->-r docs/requirements.txt (line 1)) (7.0)
Requirement already satisfied: PyYAML>=3.10 in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from mkdocs>=1.0.4->-r docs/requirements.txt (line 1)) (5.1)
Requirement already satisfied: tornado>=5.0 in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from mkdocs>=1.0.4->-r docs/requirements.txt (line 1)) (6.0.2)
Requirement already satisfied: Markdown>=2.3.1 in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from mkdocs>=1.0.4->-r docs/requirements.txt (line 1)) (3.0.1)
Requirement already satisfied: MarkupSafe>=0.23 in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from Jinja2>=2.7.1->mkdocs>=1.0.4->-r docs/requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: six in /home/docs/checkouts/readthedocs.org/user_builds/deeplodocus/envs/master/lib/python3.7/site-packages (from livereload>=2.5.1->mkdocs>=1.0.4->-r docs/requirements.txt (line 1)) (1.12.0)
```
