### ISSUE TITLE
Error message missing for failed build

### ISSUE THREAD

**Issue by AJJLagerweij** [rtfd/readthedocs.org#5647]
## Details

* Read the Docs project URL: https://topopt.readthedocs.io/en/latest/
* Build URL (if applicable): https://readthedocs.org/projects/topopt/builds/8991163/
* Read the Docs username (if applicable): AJJLagerweij

## Expected Result
Build should be passed to get the proper documentation, at least it did locally.
If any error occurs I would expect an error message.

## Actual Result
The build did fail at the `Verifying transaction: ...working...` step.
No error was shown.

**Comment by stsewd** [comment]
This is probably a time out problem, your conda requirements are a really heavy https://github.com/AJJLagerweij/topopt/blob/master/anaconda/TopOpt_Linux.yml

You can check https://docs.readthedocs.io/en/stable/guides/build-using-too-many-resources.html

**Comment by AJJLagerweij** [comment]
Thanks for your help.
In the past I've tried to run it with the pip installer only. But that resulted in other errors.
I had, among others problems with mkl-fft.
I'll try some more, and will create a new issue when I encounter new problems.

**Comment by stsewd** [comment]
I can see that your latest builds are passing and using pip, where you able to solve the problem?

**Comment by AJJLagerweij** [comment]
Hello Stsewd,
I've solved the problem for the most part, still it doesn't do exactly what I want.
I made a minimal working environment to be installed with pip.
This solved the time-out problem but brought back another one, that of python 3.7.

My code is (currently) meant for python 3.6 due to dependencies.
It runs in python 3.7 but this is detrimental for the performance (a.o. due to the lack of  mkl-fft in py3.7)

In itself this is not a problem, but I would like to be able to control the python version fur future purposes.
I've tried setting py3.6 in the `.readthedocs.yml` without using the conda envirioment:
```
# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Optionally set the version of Python and requirements required to build your docs
python:
   version: 3.6
   install:
      - requirements: docs/requirements.txt
      - method: pip
        path: .
```
But this resulted in another error: `ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.`
(If I'm correct this happened in https://readthedocs.org/projects/topopt/builds/8993164/)
